jisti se, že obsahuje všechny potřebné klíče. Měl by vypadat nějak takto:
yaml
Zkopírovat
Upravit
runtime: python310
entrypoint: gunicorn -b :$PORT opp:app

instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

env_variables:
  VALID_API_KEYS: "maxim-pidaras6944,tom-mimon22f,misa-auditt22,user4-9c6a4f7e2d1b5e8c"
  SECRET_KEY: "your-secret-key"
  DEBUG_MODE: "False"

handlers:
- url: /.*
  script: auto