runtime: python310
entrypoint: gunicorn -b :8080 full_app:app

instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

env_variables:
  CUDA_VISIBLE_DEVICES: "-1"
  VALID_API_KEYS: "maxim-pidaras6944,tom-mimon22,premium1-e5d1b9a4f7c6e3f,misa-auditt22,user4-9c6a4f7e2d1b5e8c,user1-8e3b5c6d9f1a4b7e,user2-4f9e6a7d8c2b1e3f,user3-5d8c1a4b7f9e2e6d,admin-a1b2c3d4e5f6g7h8,vip1-2e4d6f8a1b9c7e3f,test1-3e7c9a2d4f1b5e8f,guest1-6f1a9e3b7c2d5e4f,demo1-8c4f7e9a1b5d2e6f"
  SECRET_KEY: "FJGasjQaRyRKef5Gwm0dQgGxTR9_hUj9jAuHJXmnWZQ"
  DEBUG_MODE: "True"
  DEBUG: "True"

# handlers:
# - url: /.*
#   script: auto
#   secure: always