runtime: python310  # Nebo jiná verze Pythonu, např. python311

instance_class: F1  # Levná varianta, můžeš změnit na B1 nebo vyšší

entrypoint: gunicorn -b :$PORT opp:app

env_variables:
  VALID_API_KEYS: "maxim-pidaras6944,tom-mimon22f,misa-auditt22,user4-9c6a4f7e2d1b5e8c,admin-a1b2c3d4e5f6g7h8,vip1-2e4d6f8a1b9c7e3f,test1-3e7c9a2d4f1b5e8f,guest1-6f1a9e3b7c2d5e4f,demo1-8c4f7e9a1b5d2e6f,premium1-e5d1b9a4f7c6e3f"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2
  standard_scheduler_settings:
    max_instances: 2
    min_instances: 1
    target_cpu_utilization: 0.75